[build]
  command = "npm ci --prefix backend --include=dev && npm ci --prefix frontend --include=dev && npm run build --prefix frontend"
  publish = "frontend/dist"

[functions]
  directory = "backend/netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "pg", "cloudinary"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
